# =============================================================================
# CHECKOV IAC SCAN JOB
# =============================================================================
#
# Checkov is a security scanner for Infrastructure as Code
# Repository: https://github.com/bridgecrewio/checkov
#
# TO USE THIS JOB:
# 1. Copy this entire job definition into .github/workflows/iac-scan.yml
# 2. Replace the current jobs: definition with this one
# 3. The job will automatically scan all terraform files in infra/
# 4. The scan will fail if any security issues are found
# =============================================================================

jobs:
  iac-scan:
    name: IAC Scan with Checkov
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.scan-result.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Checkov IAC scanner
        id: scan-tool
        uses: bridgecrewio/checkov-action@99bb2caf247dfd9f03cf984373bc6043d4e32ebf # v12.1347.0
        with:
          directory: infra/
          framework: terraform

      - name: Set scan result
        id: scan-result
        if: always()
        run: |
          if [ "${{ steps.scan-tool.outcome }}" == "success" ]; then
            echo "result=success" >> "$GITHUB_OUTPUT"
            echo "✅ IAC scan passed - no security issues found"
          else
            echo "result=failure" >> "$GITHUB_OUTPUT"
            echo "❌ IAC scan failed - security issues detected"
            exit 1
          fi